# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/katalix/go-l2tp
%global goipath         github.com/katalix/go-l2tp
Version:                0.1.2

%gometa -f

%global common_description %{expand:
Go library for building L2TP applications on Linux systems.}

%global golicenses      LICENSE
%global godocs          doc CHANGELOG.md README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Go library for building L2TP applications on Linux systems

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/go-kit/kit/log)
BuildRequires:  golang(github.com/go-kit/kit/log/level)
BuildRequires:  golang(github.com/mdlayher/genetlink)
BuildRequires:  golang(github.com/mdlayher/netlink)
BuildRequires:  golang(github.com/mdlayher/netlink/nlenc)
BuildRequires:  golang(github.com/pelletier/go-toml)
BuildRequires:  golang(golang.org/x/sys/unix)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                                                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/*                                 %{buildroot}%{_bindir}/
install -m 0755 -vd                                                     %{buildroot}%{_mandir}/1
install -m 0755 -vp %{_builddir}/go-l2tp-%{version}/doc/kl2tpd.1        %{buildroot}%{_mandir}/1
install -m 0755 -vp %{_builddir}/go-l2tp-%{version}/doc/kpppoed.1       %{buildroot}%{_mandir}/1
install -m 0755 -vp %{_builddir}/go-l2tp-%{version}/doc/ql2tpd.1        %{buildroot}%{_mandir}/1
install -m 0755 -vd                                                     %{buildroot}%{_mandir}/5
install -m 0755 -vp %{_builddir}/go-l2tp-%{version}/doc/kl2tpd.toml.5    %{buildroot}%{_mandir}/5
install -m 0755 -vp %{_builddir}/go-l2tp-%{version}/doc/ql2tpd.toml.5   %{buildroot}%{_mandir}/5

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/*
%{_mandir}/*/*

%gopkgfiles

%changelog
%autochangelog
